### ISSUE TITLE
Implement Dummy_Scan From/To Substrait

### ISSUE THREAD

**Issue by pdet** [substrait-io/duckdb-substrait-extension#35]
In DuckDB, every query must be executed on top of a source, including queries that do not have a table as a source, like

```sql
SELECT coalesce(NULL,NULL,'test_string')
```

This is done by creating a `Dummy_Scan` underneath the projection with the coalesce expression.

I don't know how these should be represented in Substrait.

Maybe @gforsyth or @richtia know?

Related to: #1

**Comment by Tishj** [comment]
I think this could be relevant?
<https://substrait.io/relations/logical_relations/#virtual-table>

**Comment by Tishj** [comment]
By creating a virtual table in the case where no source is supplied, transforming your example into:
```sql
SELECT coalesce(expr0,expr1,expr2) from VALUES (NULL, NULL, 'test_string') T(expr0, expr1, expr2);
```
Or when a source is supplied, creating a subquery out of it and pushing the constants into it?

**Comment by pdet** [comment]
I think that makes sense. My first step here would be to check how Ibis/Isthmus represents these in the substrait json plan.

**Comment by jacques-n** [comment]
out of date, closing.
