### ISSUE TITLE
Full TPC-H support

### ISSUE THREAD

**Issue by pdet** [substrait-io/duckdb-substrait-extension#4]
I'm mainly creating this issue to keep track of where we are in the substrait TPC- Support.
There are 2 main goals here, 

1) Roundtripping Queries in DuckDB (i.e., Producing and Consuming Substrait proto queries only in DuckDB). 

2) Roundtripping Queries in DuckDB and Ibis (i.e., Ibis consuming queries produced by DuckDB, and DuckDB consuming queries produced by Ibis).

This issue will keep track of which queries are currently working and not-working.

**DuckDB Roundtrip [20/22]**

- [x] Q01
- [x] Q02
- [x] Q03
- [x] Q04
- [x] Q05
- [x] Q06
- [x] Q07
- [x] Q08
- [x] Q09
- [x] Q10
- [x] Q11
- [x] Q12
- [x] Q13
- [x] Q14
- [x] Q15
- [ ] Q16 (Substrait not supporting basic subquery flattening op: Chunk Get)
- [x] Q17
- [x] Q18
- [x] Q19
- [x] Q20
- [ ] Q21 (Substrait not supporting basic subquery flattening op: Delim Join)
- [ ] Q22 (Substrait not supporting basic subquery flattening op: Mark Join)

**Ibis (Producing) -> DuckDB (Consuming) [04/22]**
- [x] Q01
- [ ] Q02 (Ibis Compilation: 'TableArrayView)
- [ ] Q03 (Borked after Ibis/DuckDB upgrade to substrait v0.8)
- [ ] Q04 (Ibis Compilation: 'ExistsSubquery')
- [ ] Q05 (Borked after Ibis/DuckDB upgrade to substrait v0.8)
- [x] Q06
- [ ] Q07 (Ibis Compilation: (SelfReference(table=UnboundTable: nation)
- [ ] Q08 ( Ibis Compilation: (SelfReference(table=UnboundTable: nation) 
- [ ] Q09 (DuckDB Consumption: Unsupported expression type 10) 
- [ ] Q10 (Borked after Ibis/DuckDB upgrade to substrait v0.8)
- [ ] Q11 (Wrong results)
- [x] Q12
- [ ] Q13 (DuckDB Consumption: Catalog Error: Scalar Function with name not does not exist!)
- [ ] Q14 (Ibis Compilation: Parameter to MergeFrom() must be instance of same class: expected substrait.Expression got substrait) 
- [ ] Q15 (Ibis Compilation: non-empty child_rel_field_offsets passed in to selection translation rule) 
- [ ] Q16 (Ibis Compilation: 'IntegerColumn' object is not iterable) 
- [ ] Q17 (Ibis Compilation: <class 'ibis.expr.operations.relations.Aggregation'>) 
- [ ] Q18 (Ibis Compilation: 'IntegerColumn' object is not iterable) 
- [x] Q19
- [ ] Q20 (Ibis Compilation: 'IntegerColumn' object is not iterable) 
- [ ] Q21 (Ibis Compilation: 'ExistsSubquery')
- [ ] Q22 (Ibis Compilation: 'NotExistsSubquery')

**DuckDB (Producing) -> Ibis (Consuming)** (WIP) [0/22]
- [ ] Q01 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q02 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q03 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q04 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q05 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q06 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q07 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q08 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q09 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q10 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q11 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q12 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q13 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q14 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q15 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q16 (Substrait not supporting basic subquery flattening op: Chunk Get)
- [ ] Q17 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q18 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q19 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q20 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q21 (Substrait not supporting basic subquery flattening op: Delim Join)
- [ ] Q22 (Substrait not supporting basic subquery flattening op: Chunk Get)

**Comment by jacques-n** [comment]
out of date, closing.
