### ISSUE TITLE
Support temporal functions duckdb - ibis

### ISSUE THREAD

**Issue by pdet** [substrait-io/duckdb-substrait-extension#50]
https://github.com/substrait-io/substrait/pull/322

**Comment by Tishj** [comment]
<https://github.com/substrait-io/substrait/pull/272>

**Comment by Tishj** [comment]
<https://github.com/duckdb/duckdb/issues/6805>
Some functionality is missing in core to support all of these components, made an issue for it ^

**Comment by pdet** [comment]
With the latest upgrade to substrait 0.35, we should be able to continue this issue.

https://github.com/duckdb/duckdb/issues/6805#issuecomment-1695852085

**Comment by jacques-n** [comment]
out of date, closing.
